### ISSUE TITLE
Some troubles in v0.1.16

### ISSUE THREAD

**Issue by h0le** [rkoeninger/sublime-factor#21]
v0.1.16 confuse me a little.
This is how your screenshot example looks on my system:
![bug-01](https://user-images.githubusercontent.com/4871017/45473972-d22fab80-b77b-11e8-96c1-2ba9109451fb.png)

And some more test cases:
![bug-01](https://user-images.githubusercontent.com/4871017/45476060-59335280-b781-11e8-93b8-6d7f2593eb93.png)
Is it bugs or features?

PS. I would inform you, that Language Server Protocol implementation planned in .99 https://github.com/factor/factor/issues/2039 .  And besides Language Server Protocol available in ST3 via plugin https://packagecontrol.io/packages/LSP . What you think?

**Comment by rkoeninger** [comment]
Screenshot in readme shows what the `example.factor` is supposed to look like. Screenshot is in Marina color scheme. I scroll through different color schemes as they highlight code differently, not just in different colors. In some color schemes (maybe the one you're using), function parameters don't get any highlighting and the words in a stack effect are labelled as parameters.

![screenshot](https://raw.githubusercontent.com/rkoeninger/sublime-factor/master/screenshot.png)

Everything in that screenshot looks right to me. (Except for the string following OTHERDIRECTIVE:)

---

Top-level expressions don't get highlighted. I don't know if that's needed or not. (i see unit testing examples use top-level expressions) Expressions only get highlighted in definitions and certain directives.

I think TUPLE: has to be semicolon terminated, that's what is shows [in the docs](https://docs.factorcode.org/content/word-TUPLE__colon__,syntax.html). Are you using the latest version of Factor? I'm trying your `TUPLE: a L{ 1 2 3 }` in the listener right now and it's telling me that's wrong.

The thing with ARTICLE: is screwed up, the matching of operators vs strings and numbers is in the wrong order. I'll fix that.

Highlighting will work differently in directives like SYNTAX: because it won't try to match braces and will instead just consider them operators. Braces might be used in a directive without being matched, having the highlighting count on them being matched would screw things up.

Problem is, Factor is a very flexible language in which anything can be an identifier and get used in almost any context. I might need to simplify the syntax instead of trying to handle more and more special cases.

---

If they make an LSP for Factor, I would consider this plugin obsolete.

**Comment by rkoeninger** [comment]
I just released v0.1.17 which addressed some of these issues

**Comment by h0le** [comment]
> TUPLE: has to be semicolon terminated

You are right.

**Comment by h0le** [comment]
In v0.1.17 it looks like:
![bug-01](https://user-images.githubusercontent.com/4871017/45504849-54e15680-b7ce-11e8-9a30-825d6446f8c1.png)

**Comment by rkoeninger** [comment]
The stack effect highlighting might be because of your color scheme. Here's what it looks like in Monokai:

![image](https://user-images.githubusercontent.com/6507761/45511170-36e20a80-b76a-11e8-8853-01b5e1bcca1e.png)

**Comment by rkoeninger** [comment]
@v0idNULL Anything else? FYI, there's a 0.1.18 release now.

**Comment by h0le** [comment]
That's all. On my system 0.1.18 gives the same as 0.1.17.
